# Generated by Django 2.0.2 on 2018-02-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuliza_cart', '0002_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item_name',
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
