# Generated by Django 2.0.2 on 2018-02-11 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuliza_cart', '0005_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='productImages')),
                ('price', models.FloatField(default=0)),
                ('user', models.IntegerField(blank=True, null=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kuliza_cart.ItemSubCategory')),
            ],
        ),
    ]
